### ISSUE TITLE
updated version download

### ISSUE THREAD

**Issue by foss-lover34** [LynxDev2/smo-galaxy-spin#15]
hey man, love ythsi mod. thanks. i see from gamebana version 2.0 finally released giving you air time, but the download on gamebanana is the old one from 3 months ago and still flagged as 1.0 altough you can see the 2.0 changelog update. also would suggest to add releases of the mod here in github. anyways please update the link from gamebanana correctly <3

**Comment by LynxDev2** [comment]
Yep, the gamebanana page is a bit confusing. We were gonna release 2.0 a while ago but kept finding more and more new things to fix. There’s still one configuration related feature I want to add and after that I’ll probably make a prerelease here on github. Then once we test everything it’ll be on gamebanana

**Comment by LynxDev2** [comment]
In the meantime, there are instructions on how to build the mod, so you can always get the latest version

**Comment by foss-lover34** [comment]
nah fam i dont fuck around with building stuff. im just very excited for the air time version and cat wait to try. please upload asap <3<3
